### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alekitto** [fazland/fatture-in-cloud-sdk#10]
From the official documentation: https://api.fattureincloud.it/v1/documentation/dist
Here's the list of what is missing in this library.

# Resources
## Product
- [ ] Product list
- [ ] Product new/edit
- [ ] Product delete
- [ ] Product bulk insert

## Document
- [ ] Documents Info
- [ ] Document email sending

## Purchase
- [ ] Purchase list
- [ ] Purchase new/edit
- [ ] Purchase delete

## Fee
- [ ] Fee list
- [ ] Fee new/edit
- [ ] Fee delete

## Warehouse
- [ ] Arrival list
- [ ] Arrival detail

## Email
- [ ] Email archive list

## Info
- [ ] Misc data

# Documentation
- [ ] Everything

# Tests
- [ ] Everything 😄
